-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
--
-- Add any additional autocmds here
-- with `vim.api.nvim_create_autocmd`
--
-- Or remove existing autocmds by their group name (which is prefixed with `lazyvim_` for the defaults)
-- e.g. vim.api.nvim_del_augroup_by_name("lazyvim_wrap_spell")

-- Add a way to build and run a test (generated by Claude Sonnet 5)
vim.api.nvim_create_user_command("CMakeGBTest", function(opts)
  local cmake = require("cmake-tools")
  local args = opts.args
  cmake.generate({ bang = false }, function()
    cmake.build({ bang = false }, function()
      vim.cmd("CMakeRunTest" .. args)
    end)
  end)
end, { nargs = "*", desc = "CMake: Build and Test" })
